# Generated by Django 5.0.4 on 2024-04-17 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='url',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
